# Generated by Django 4.2.7 on 2024-03-04 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=130)),
                ('project_image', models.ImageField(max_length=130, upload_to='')),
                ('project_description', models.TextField(max_length=500)),
                ('github_link', models.CharField(max_length=230)),
            ],
        ),
        migrations.CreateModel(
            name='UpcommingProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=130)),
                ('project_image', models.ImageField(max_length=130, upload_to='')),
                ('project_description', models.TextField(max_length=500)),
                ('github_link', models.CharField(max_length=230)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=130)),
                ('Job_title', models.CharField(max_length=130)),
                ('work_description', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_level', models.CharField(max_length=130)),
                ('qualification', models.CharField(max_length=130)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myprofile.institution')),
            ],
        ),
    ]
