# Generated by Django 4.2.7 on 2024-03-04 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0003_alter_education_end_date_alter_education_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='project_description',
            field=models.TextField(max_length=1500),
        ),
    ]
