# Generated by Django 4.2.7 on 2024-03-05 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0004_alter_projects_project_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraph1', models.CharField(max_length=1030)),
                ('paragraph2', models.CharField(max_length=1030)),
                ('paragraph3', models.CharField(max_length=1030)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programing_language', models.CharField(max_length=1030)),
                ('learning_progress', models.IntegerField()),
            ],
        ),
    ]
