# Generated by Django 4.2.7 on 2024-03-05 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0005_aboutme_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='paragraph1',
            field=models.TextField(max_length=1030),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='paragraph2',
            field=models.TextField(max_length=1030),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='paragraph3',
            field=models.TextField(max_length=1030),
        ),
    ]
