# Generated by Django 4.2.7 on 2024-03-05 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0006_alter_aboutme_paragraph1_alter_aboutme_paragraph2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upcommingprojects',
            name='project_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
