# Generated by Django 4.2.7 on 2024-03-05 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0007_alter_upcommingprojects_project_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upcommingprojects',
            name='project_image',
        ),
    ]
