# Generated by Django 4.2.7 on 2024-03-05 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0008_remove_upcommingprojects_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='upcommingprojects',
            name='project_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
